# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frankstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='prize',
            field=models.CharField(default='kshs.', max_length=60),
        ),
    ]
