# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-17 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frankstore', '0009_profile_adverts_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adverts_count',
            new_name='advertscount',
        ),
    ]
